In [1]:
import numpy as np
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, KFold, cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.utils import shuffle

In [2]:
A = np.loadtxt("datasets-part1/tictac_final.txt")
B = np.loadtxt("datasets-part1/tictac_single.txt")
C = np.loadtxt("datasets-part1/tictac_multi.txt")

In [3]:
A = shuffle(A)
X = A[:, :9]
Y = A[:, 9:]

B = shuffle(B)
X1 = B[:, :9]
Y1 = B[:, 9:]

C = shuffle(C)
X2 = C[:, :9]
Y2 = C[:, 9:]

In [4]:
classifiers = [SVC(kernel='linear'), KNeighborsClassifier(n_neighbors=3), 
               MLPClassifier(hidden_layer_sizes=(100, 50), alpha=0.0001, max_iter=300)]

In [5]:
def model_evaluation(X_t, Y_t):
    X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
    for classifier in classifiers:
        classifier.fit(X_train, Y_train)
        y_predict = classifier.predict(X_test)
        kf = KFold(n_splits=10, shuffle=True, random_state=42) 
        
        accuracyScore = accuracy_score(Y_test, y_predict)
        crossValScores = cross_val_score(classifier, X_train, Y_train, cv=kf)
        confusionMatrix = confusion_matrix(Y_test, y_predict)
        print('Classifier Name:', classifier)
        print('Accuracy Score:', accuracyScore * 100)
        print('Cross Validation Accuracy:', crossValScores.mean() * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [6]:
model_evaluation(X, Y)

C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Classifier Name: SVC(kernel='linear')
Accuracy Score: 97.39583333333334
Cross Validation Accuracy: 98.56288448393711
Confusion Matrix 
 [[ 77   5]
 [  0 110]]

Classifier Name: KNeighborsClassifier(n_neighbors=3)
Accuracy Score: 100.0
Cross Validation Accuracy: 99.86842105263158
Confusion Matrix 
 [[ 82   0]
 [  0 110]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y 

Classifier Name: MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=300)
Accuracy Score: 98.4375
Cross Validation Accuracy: 98.82262474367737
Confusion Matrix 
 [[ 79   3]
 [  0 110]]



In [7]:
def model_evaluation_classifier(X_t, Y_t):
    X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
    for classifier in classifiers:
        classifier.fit(X_train, Y_train)
        y_predict = classifier.predict(X_test)
        kf = KFold(n_splits=10, shuffle=True, random_state=42)
        
        accuracyScore = accuracy_score(Y_test, y_predict)
        crossValScores = cross_val_score(classifier, X_train, Y_train, cv=kf)
        confusionMatrix = confusion_matrix(Y_test, y_predict)
        print('Classifier Name:', classifier)
        print('Accuracy Score', accuracyScore * 100)
        print('Cross Validation Accuracy:', crossValScores.mean() * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [8]:
model_evaluation_classifier(X1, Y1)

C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Classifier Name: SVC(kernel='linear')
Accuracy Score 39.28299008390542
Cross Validation Accuracy: 37.04198473282443
Confusion Matrix 
 [[330   0   0   0   0   0   0   0   0]
 [ 90  34  14   0  39   0   0   0   0]
 [ 92   0  64   0  36   0   0   0   0]
 [ 39  14   9   1  14   0   0   0   0]
 [130   0   0   0  86   0   0   0   0]
 [ 44   9   7   0   5   0   0   0   0]
 [ 57  19  17   9   9   0   0   0   0]
 [ 34   8   2   0   2   0   0   0   0]
 [ 62  15  15   0   5   0   0   0   0]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

Classifier Name: KNeighborsClassifier(n_neighbors=3)
Accuracy Score 76.12509534706331
Cross Validation Accuracy: 74.06488549618321
Confusion Matrix 
 [[274  12  11   7   8   1   8   2   7]
 [ 16 121   6   2  14   4   5   3   6]
 [ 13  11 151   4  10   0   1   0   2]
 [  5   4   3  54   3   0   4   1   3]
 [ 16   7  12   3 177   0   1   0   0]
 [  6   4   4   3   3  41   1   2   1]
 [ 17   6   3   1   1   1  81   0   1]
 [  5   4   4   1   1   0   0  28   3]
 [ 12   3   2   2   3   3   1   0  71]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization h

Classifier Name: MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=300)
Accuracy Score 94.12662090007628
Cross Validation Accuracy: 92.25190839694658
Confusion Matrix 
 [[305   4   6   2   8   1   4   0   0]
 [  0 165   2   0   2   1   3   2   2]
 [  4   1 180   3   0   3   0   1   0]
 [  0   0   0  69   1   2   1   3   1]
 [  0   1   1   0 214   0   0   0   0]
 [  0   0   0   2   2  59   0   0   2]
 [  1   2   0   0   0   0 108   0   0]
 [  3   0   0   0   0   0   0  43   0]
 [  1   2   3   0   0   0   0   0  91]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


In [9]:
regressors = [KNeighborsRegressor(n_neighbors=3), LinearRegression(), 
              MLPRegressor(hidden_layer_sizes=(100, 50), alpha=0.0001, max_iter=300)]

In [10]:
def model_evaluation_regression(X_t, Y_t):
    for regressor in regressors: 
        X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
        regressor.fit(X_train, Y_train)
        y_predict = regressor.predict(X_test)
        predClasses = np.argmax(y_predict, axis=1)
        predTrue = np.argmax(Y_test, axis=1)
        accuracyScore = accuracy_score(predTrue, predClasses)
        confusionMatrix = confusion_matrix(predTrue, predClasses)
        
        maeError = mean_absolute_error(Y_test, y_predict)
        mseError = mean_squared_error(Y_test, y_predict)
        r2Score = r2_score(Y_test, y_predict)
        print('Classifier Name:', regressor)
        print('Accuracy Score: ', accuracyScore * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('Mean Absolute Error: ', maeError)
        print('Mean Squared Error: ', mseError)
        print('R2 Score: ', r2Score)
        print('')

In [11]:
model_evaluation_regression(X2, Y2)

Classifier Name: KNeighborsRegressor(n_neighbors=3)
Accuracy Score:  72.99771167048054
Confusion Matrix 
 [[212  17  24  11  23   6  14   4   9]
 [  6 113  21  11  16   4   7   6   5]
 [  6   3 132   6  10   0   7   5   8]
 [  2   1   0  61  12   2   5   5   2]
 [  2   7   4   5 186   3   2   6   4]
 [  1   2   1   1   1  50   2   2   2]
 [  3   1   5   6   2   2  83   2   1]
 [  0   0   0   0   0   1   3  32   5]
 [  8   3   0   0   4   2   2   1  88]]
Mean Absolute Error:  0.13068904144419025
Mean Squared Error:  0.07138081381661372
R2 Score:  0.5612213229556409

Classifier Name: LinearRegression()
Accuracy Score:  18.459191456903127
Confusion Matrix 
 [[ 20   0  37   2 209   0  36   0   0]
 [ 21   0  13   0 121   0  19   0   3]
 [ 16   0  21   0 114   0   4   0   4]
 [ 14   0   9   0  67   0  25   0   0]
 [ 24   0   6   0 180   0   5   0   3]
 [ 11   0   9   0  38   0   5   0   0]
 [ 13   0   8   0  78   0  21   0   0]
 [ 10   0   8   0  28   0  11   0   0]
 [  7   0  13   0  66   0