In [1]:
import numpy as np
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, KFold, cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [2]:
A = np.loadtxt("datasets-part1/tictac_final.txt")
B = np.loadtxt("datasets-part1/tictac_single.txt")
C = np.loadtxt("datasets-part1/tictac_multi.txt")

In [3]:
X = A[:, :9]
Y = A[:, 9:]

X1 = B[:, :9]
Y1 = B[:, 9:]

X2 = C[:, :9]
Y2 = C[:, 9:]

In [4]:
classifiers = [SVC(kernel='linear'), KNeighborsClassifier(), MLPClassifier()]

In [5]:
def model_evaluation(X_t, Y_t):
    X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
    for classifier in classifiers:
        classifier.fit(X_train, Y_train)
        y_predict = classifier.predict(X_test)
        kf = KFold(n_splits=10, shuffle=True) 
        
        accuracyScore = accuracy_score(Y_test, y_predict)
        crossValScores = cross_val_score(classifier, X_train, Y_train, cv=kf)
        confusionMatrix = confusion_matrix(Y_test, y_predict)
        print('Classifier Name:', classifier)
        print('Accuracy Score:', accuracyScore * 100)
        print('Cross Validation Accuracy:', crossValScores.mean() * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [6]:
model_evaluation(X, Y)

C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Classifier Name: SVC(kernel='linear')
Accuracy Score: 97.91666666666666
Cross Validation Accuracy: 98.43130553656869
Confusion Matrix 
 [[ 58   4]
 [  0 130]]

Classifier Name: KNeighborsClassifier()
Accuracy Score: 100.0
Cross Validation Accuracy: 99.34552289815446
Confusion Matrix 
 [[ 62   0]
 [  0 130]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using rave

Classifier Name: MLPClassifier()
Accuracy Score: 97.91666666666666
Cross Validation Accuracy: 98.43301435406697
Confusion Matrix 
 [[ 58   4]
 [  0 130]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [7]:
def model_evaluation_classifier(X_t, Y_t):
    X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
    for classifier in classifiers:
        classifier.fit(X_train, Y_train)
        y_predict = classifier.predict(X_test)
        kf = KFold(n_splits=10, shuffle=True)
        
        accuracyScore = accuracy_score(Y_test, y_predict)
        crossValScores = cross_val_score(classifier, X_train, Y_train, cv=kf)
        confusionMatrix = confusion_matrix(Y_test, y_predict)
        print('Classifier Name:', classifier)
        print('Accuracy Score', accuracyScore * 100)
        print('Cross Validation Accuracy:', crossValScores.mean() * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [8]:
model_evaluation_classifier(X1, Y1)

C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Classifier Name: SVC(kernel='linear')
Accuracy Score 36.231884057971016
Cross Validation Accuracy: 36.603053435114504
Confusion Matrix 
 [[320   0   0   0   0   0   0   0   0]
 [ 84  20  40   0  23   0   0   0   0]
 [109   0  57   0  25   0   0   0   0]
 [ 48   9  18   4   9   0   0   0   0]
 [142   0   0   0  74   0   0   0   0]
 [ 41  10  16   0   4   0   0   0   0]
 [ 58   3  23   3   9   0   0   0   0]
 [ 44   8   8   0   5   0   0   0   0]
 [ 52   8  29   0   8   0   0   0   0]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

Classifier Name: KNeighborsClassifier()
Accuracy Score 75.13348588863464
Cross Validation Accuracy: 74.46564885496183
Confusion Matrix 
 [[266   8   6   8  14   1  12   3   2]
 [  7 110  12  11   9   6   6   2   4]
 [ 22  11 140   2   6   2   4   3   1]
 [  5   5   3  66   3   1   2   0   3]
 [ 17   9   9   4 175   1   1   0   0]
 [  5   8   1   1   1  51   3   1   0]
 [ 10   5   4   3   1   1  72   0   0]
 [  7   4   2   3   0   2   4  40   3]
 [ 10   2   3   2   9   1   2   3  65]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization h

Classifier Name: MLPClassifier()
Accuracy Score 86.65141113653699
Cross Validation Accuracy: 86.31679389312978
Confusion Matrix 
 [[293   5   4   4   8   2   2   1   1]
 [  2 131   8   7  11   4   4   0   0]
 [ 14   6 164   4   1   0   1   1   0]
 [  2   1   0  73   6   0   3   2   1]
 [ 12   4   0   3 194   1   0   0   2]
 [  2   5   1   1   0  56   4   2   0]
 [  5   3   1   4   0   0  83   0   0]
 [  1   0   2   2   0   0   1  57   2]
 [  5   2   1   1   0   3   0   0  85]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [9]:
regressors = [KNeighborsRegressor(n_neighbors=3), LinearRegression(), MLPRegressor()]

In [10]:
def model_evaluation_regression(X_t, Y_t):
    for regressor in regressors: 
        X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
        regressor.fit(X_train, Y_train)
        y_predict = regressor.predict(X_test)
        predClasses = np.argmax(y_predict, axis=1)
        predTrue = np.argmax(Y_test, axis=1)
        accuracyScore = accuracy_score(predTrue, predClasses)
        confusionMatrix = confusion_matrix(predTrue, predClasses)
        
        maeError = mean_absolute_error(Y_test, y_predict)
        mseError = mean_squared_error(Y_test, y_predict)
        r2Score = r2_score(Y_test, y_predict)
        print('Classifier Name:', regressor)
        print('Accuracy Score: ', accuracyScore * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('Mean Absolute Error: ', maeError)
        print('Mean Squared Error: ', mseError)
        print('R2 Score: ', r2Score)
        print('')

In [11]:
model_evaluation_regression(X2, Y2)

Classifier Name: KNeighborsRegressor(n_neighbors=3)
Accuracy Score:  73.22654462242562
Confusion Matrix 
 [[213   8  23   8  18  11  15   7   9]
 [ 10 114   9   6  17   7  10   6  12]
 [  5   2 146  10  12   0  16   4  12]
 [  1   0   6  67  11   2   9   2   3]
 [  7   2   1   3 174   1   3   3   5]
 [  0   3   3   1   0  58   5   2   7]
 [  1   2   1   3   2   0  79   3   3]
 [  0   1   1   2   0   0   1  34   2]
 [  4   2   1   2   1   1   0   1  75]]
Mean Absolute Error:  0.13057603751730387
Mean Squared Error:  0.0711736399506552
R2 Score:  0.5714371942615794

Classifier Name: LinearRegression()
Accuracy Score:  17.696414950419527
Confusion Matrix 
 [[ 29   0  15   0 239   0  31   0   2]
 [ 23   0   4   0 129   0  14   0  11]
 [ 16   0   6   0 158   0   6   0  19]
 [  6   0   6   0  70   0  12   0   3]
 [ 19   0   0   0 187   0   6   0   3]
 [  8   0   9   0  35   0   8   0   7]
 [ 10   0   2   0  70   0   9   0   6]
 [  7   0   6   0  30   0   4   0   4]
 [  4   0  13   0  55   0 