In [1]:
import numpy as np
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, KFold, cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.utils import shuffle

In [2]:
A = np.loadtxt("datasets-part1/tictac_final.txt")
B = np.loadtxt("datasets-part1/tictac_single.txt")
C = np.loadtxt("datasets-part1/tictac_multi.txt")

In [3]:
A = shuffle(A)
X = A[:, :9]
Y = A[:, 9:]

B = shuffle(B)
X1 = B[:, :9]
Y1 = B[:, 9:]

C = shuffle(C)
X2 = C[:, :9]
Y2 = C[:, 9:]

In [4]:
classifiers = [SVC(kernel='linear'), KNeighborsClassifier(), MLPClassifier()]

In [5]:
def model_evaluation(X_t, Y_t):
    X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
    for classifier in classifiers:
        classifier.fit(X_train, Y_train)
        y_predict = classifier.predict(X_test)
        kf = KFold(n_splits=10, shuffle=True, random_state=42) 
        
        accuracyScore = accuracy_score(Y_test, y_predict)
        crossValScores = cross_val_score(classifier, X_train, Y_train, cv=kf)
        confusionMatrix = confusion_matrix(Y_test, y_predict)
        print('Classifier Name:', classifier)
        print('Accuracy Score:', accuracyScore * 100)
        print('Cross Validation Accuracy:', crossValScores.mean() * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [6]:
model_evaluation(X, Y)

C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Classifier Name: SVC(kernel='linear')
Accuracy Score: 96.35416666666666
Cross Validation Accuracy: 98.81920710868079
Confusion Matrix 
 [[ 63   7]
 [  0 122]]

Classifier Name: KNeighborsClassifier()
Accuracy Score: 100.0
Cross Validation Accuracy: 99.73684210526315
Confusion Matrix 
 [[ 70   0]
 [  0 122]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using rave

Classifier Name: MLPClassifier()
Accuracy Score: 96.35416666666666
Cross Validation Accuracy: 98.81920710868079
Confusion Matrix 
 [[ 63   7]
 [  0 122]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [7]:
def model_evaluation_classifier(X_t, Y_t):
    X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
    for classifier in classifiers:
        classifier.fit(X_train, Y_train)
        y_predict = classifier.predict(X_test)
        kf = KFold(n_splits=10, shuffle=True, random_state=42)
        
        accuracyScore = accuracy_score(Y_test, y_predict)
        crossValScores = cross_val_score(classifier, X_train, Y_train, cv=kf)
        confusionMatrix = confusion_matrix(Y_test, y_predict)
        print('Classifier Name:', classifier)
        print('Accuracy Score', accuracyScore * 100)
        print('Cross Validation Accuracy:', crossValScores.mean() * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [8]:
model_evaluation_classifier(X1, Y1)

C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Classifier Name: SVC(kernel='linear')
Accuracy Score 44.927536231884055
Cross Validation Accuracy: 40.99236641221374
Confusion Matrix 
 [[308   0   0   0   0   0   0   0   0]
 [ 25  27  55   0  55   0   0   0   0]
 [ 49   0  97   0  59   0   0   0   0]
 [ 14  14  32  11  27   0   0   0   0]
 [ 64   0   0   5 143   0   0   0   0]
 [ 21  13  28   1  13   0   0   0   0]
 [ 34  15  27   7  16   0   3   0   0]
 [ 24  14  11   0  10   0   0   0   0]
 [ 36  10  31   2  10   0   0   0   0]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

Classifier Name: KNeighborsClassifier()
Accuracy Score 73.30282227307399
Cross Validation Accuracy: 74.38931297709924
Confusion Matrix 
 [[262   6  14   7   7   0   4   2   6]
 [ 10 114   7   5  13   3   1   2   7]
 [ 18  14 154   7   5   2   2   0   3]
 [ 10   7   7  64   4   3   1   1   1]
 [ 28   7  10   7 158   0   1   0   1]
 [  5   6   6   2   2  51   3   1   0]
 [ 17   6   4   1   3   2  68   0   1]
 [  4   6   1   1   5   1   2  39   0]
 [ 14   5   4   5   7   2   1   0  51]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using rave

Classifier Name: MLPClassifier()
Accuracy Score 87.03279938977879
Cross Validation Accuracy: 85.9351145038168
Confusion Matrix 
 [[284   0   8   1   6   2   0   3   4]
 [  1 134   6   5   5   3   5   0   3]
 [  6   5 181   4   5   1   2   0   1]
 [  5   0   1  78   2   2   7   2   1]
 [  7   5   5   3 186   2   2   0   2]
 [  2   0   0   3   1  66   1   3   0]
 [  6   2   2   1   0   0  89   2   0]
 [  1   3   1   2   3   0   3  46   0]
 [  3   0   0   1   3   2   3   0  77]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [9]:
regressors = [KNeighborsRegressor(n_neighbors=3), LinearRegression(), MLPRegressor()]

In [10]:
def model_evaluation_regression(X_t, Y_t):
    for regressor in regressors: 
        X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
        regressor.fit(X_train, Y_train)
        y_predict = regressor.predict(X_test)
        predClasses = np.argmax(y_predict, axis=1)
        predTrue = np.argmax(Y_test, axis=1)
        accuracyScore = accuracy_score(predTrue, predClasses)
        confusionMatrix = confusion_matrix(predTrue, predClasses)
        
        maeError = mean_absolute_error(Y_test, y_predict)
        mseError = mean_squared_error(Y_test, y_predict)
        r2Score = r2_score(Y_test, y_predict)
        print('Classifier Name:', regressor)
        print('Accuracy Score: ', accuracyScore * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('Mean Absolute Error: ', maeError)
        print('Mean Squared Error: ', mseError)
        print('R2 Score: ', r2Score)
        print('')

In [11]:
model_evaluation_regression(X2, Y2)

Classifier Name: KNeighborsRegressor(n_neighbors=3)
Accuracy Score:  72.46376811594203
Confusion Matrix 
 [[217   4  22  15  16  10  15  11  14]
 [  0  89  14   8  23   3  10   5   8]
 [  5   7 154   5  14   8  10   5   8]
 [  3   2   1  67   9   3   4   2   5]
 [  1   8   3   0 168   2   8   1   4]
 [  1   2   2   2   1  49   0   2   5]
 [  2   2   5   5   3   4  88   1   1]
 [  0   1   2   1   0   0   0  41   4]
 [  3   0   3   2   3   5   1   2  77]]
Mean Absolute Error:  0.12879622566884208
Mean Squared Error:  0.07114538896893356
R2 Score:  0.57106753516924

Classifier Name: LinearRegression()
Accuracy Score:  17.391304347826086
Confusion Matrix 
 [[ 13   0  27   0 188   0  61   0   1]
 [ 14   0  16   0 107   0  22   0   1]
 [ 27   0  18   0 125   0  15   0   6]
 [ 14   0  10   0  56   0  19   0   0]
 [ 30   0   1   0 189   0  12   0   3]
 [ 11   0   3   0  53   0  12   0   3]
 [ 17   0   5   2  83   0   8   0   1]
 [  9   0   5   0  29   0   5   0   1]
 [ 12   0  11   0  61   0  