In [1]:
import numpy as np
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, KFold, cross_val_predict
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# add the cross val accuracy using "cross_val_score" for classifiers and "r2_mean" for regressors

In [2]:
A = np.loadtxt("datasets-part1/tictac_final.txt")
B = np.loadtxt("datasets-part1/tictac_single.txt")
C = np.loadtxt("datasets-part1/tictac_multi.txt")

In [3]:
X = A[:, :9]
Y = A[:, 9:]

X1 = B[:, :9]
Y1 = B[:, 9:]

X2 = C[:, :9]
Y2 = C[:, 9:]

In [4]:
classifiers = [SVC(kernel='linear'), KNeighborsClassifier(), MLPClassifier()]

In [5]:
def model_evaluation(X_t, Y_t):
    X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
    for classifier in classifiers:
        classifier.fit(X_train, Y_train)
        y_predict = classifier.predict(X_test)
        accuracyScore = accuracy_score(Y_test, y_predict)
        confusionMatrix = confusion_matrix(Y_test, y_predict)
        print('Classifier Name:', classifier)
        print('Accuracy Score', accuracyScore * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [6]:
model_evaluation(X, Y)

C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Classifier Name: SVC(kernel='linear')
Accuracy Score 98.95833333333334
Confusion Matrix 
 [[ 62   2]
 [  0 128]]

Classifier Name: KNeighborsClassifier()
Accuracy Score 100.0
Confusion Matrix 
 [[ 64   0]
 [  0 128]]

Classifier Name: MLPClassifier()
Accuracy Score 98.95833333333334
Confusion Matrix 
 [[ 62   2]
 [  0 128]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [7]:
def model_evaluation_classifier(X_t, Y_t):
    X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
    for classifier in classifiers:
        classifier.fit(X_train, Y_train)
        y_predict = classifier.predict(X_test)
        accuracyScore = accuracy_score(Y_test, y_predict)
        confusionMatrix = confusion_matrix(Y_test, y_predict)
        print('Classifier Name:', classifier)
        print('Accuracy Score', accuracyScore * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [8]:
model_evaluation_classifier(X1, Y1)

C:\Users\prane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Classifier Name: SVC(kernel='linear')
Accuracy Score 38.062547673531654
Confusion Matrix 
 [[325   0   0   0   0   0   0   0   0]
 [ 74  25  28   0  32   0   0   0   0]
 [102   0  58   0  32   0   0   0   0]
 [ 59   7  14   0  18   0   0   0   0]
 [118   0   0   0  91   0   0   0   0]
 [ 41   5  17   0   6   0   0   0   0]
 [ 67   5  26   1   9   0   0   0   0]
 [ 34  10   7   0   2   0   0   0   0]
 [ 57   3  31   0   7   0   0   0   0]]

Classifier Name: KNeighborsClassifier()
Accuracy Score 74.59954233409611
Confusion Matrix 
 [[283   5   7   3  15   1   8   0   3]
 [ 11 107   8   7  12   3   4   2   5]
 [ 16   5 148   5   6   1   1   1   9]
 [  5   7   6  65   6   0   3   2   4]
 [ 20   6   9   7 157   2   3   1   4]
 [  6   6   3   3   2  49   0   0   0]
 [ 12   4   5   7   2   1  77   0   0]
 [  5   4   0   4   4   1   2  28   5]
 [ 14   1   6   4   5   4   0   0  64]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Classifier Name: MLPClassifier()
Accuracy Score 86.49885583524028
Confusion Matrix 
 [[287   3   6   4  13   2   5   1   4]
 [  4 133   7   4   5   4   2   0   0]
 [  5   3 172   4   6   1   0   0   1]
 [  4   3   3  77   5   1   1   1   3]
 [  4   0   4   2 190   1   5   0   3]
 [  1   2   2   2   0  59   0   3   0]
 [  8   0   2   7   1   0  85   2   3]
 [  1   1   1   0   0   2   0  46   2]
 [  4   2   1   1   2   3   0   0  85]]



C:\Users\prane\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [9]:
regressors = [KNeighborsRegressor(n_neighbors=3), LinearRegression(), MLPRegressor()]

In [10]:
def model_evaluation_regression(X_t, Y_t):
    for regressor in regressors: 
        X_train, X_test, Y_train, Y_test = train_test_split(X_t, Y_t, test_size=0.2)
        regressor.fit(X_train, Y_train)
        y_predict = regressor.predict(X_test)
        predClasses = np.argmax(y_predict, axis=1)
        predTrue = np.argmax(Y_test, axis=1)
        accuracyScore = accuracy_score(predTrue, predClasses)
        confusionMatrix = confusion_matrix(predTrue, predClasses)
        print('Classifier Name:', regressor)
        print('Accuracy Score: ', accuracyScore * 100)
        print('Confusion Matrix \n', confusionMatrix)
        print('')

In [11]:
model_evaluation_regression(X2, Y2)

Classifier Name: KNeighborsRegressor(n_neighbors=3)
Accuracy Score:  74.4469870327994
Confusion Matrix 
 [[207   8  21   5  17   2  12   6  13]
 [  7 108  16   8  22   2   9   6   5]
 [  3   2 139   6  11   5  10   1  11]
 [  6   3   0  61  16   0   6   3   5]
 [  7   1   3   1 207   0   4   2   8]
 [  2   6   1   4   1  48   2   3   3]
 [  1   6   4   1   2   0  89   2   4]
 [  0   2   1   2   1   0   1  39   3]
 [  2   1   3   0   0   1   2   1  78]]

Classifier Name: LinearRegression()
Accuracy Score:  16.09458428680397
Confusion Matrix 
 [[ 12   0  15   0 269   0  18   0   5]
 [ 20   0   5   0 130   0  12   0  11]
 [ 11   0  16   0 152   0   0   0  17]
 [  3   0   7   0  63   0  10   0   4]
 [  7   0   2   0 175   0   7   0   1]
 [  5   0   0   0  36   0   8   0  10]
 [  6   0   3   0 102   0   5   0   6]
 [  3   0  10   0  33   0   8   0   1]
 [  3   0   5   0  80   0  12   0   3]]

Classifier Name: MLPRegressor()
Accuracy Score:  69.48893974065598
Confusion Matrix 
 [[159   3  25